language: java
sudo: false
jdk:
- oraclejdk8
env:
  global:
  - secure: bT1lpgLsR/HIXG4qgR+dnYS0dGhTzu1Y1atoRs/71pFhykTwXH4A9kPyIV3q2XWUH4IAl7nwbOAC5X22RgqfpXhZI5r1qPkw7nncoNKF+CU37DPmG9JWUNTnJmJNva8e6WZ6flneMOTzx/u8tcV+vhH1+MLPzrYdH/c4W60HBrQF1WlXkOGBSHRr+p4bNvzglSX4w2bIGLRW6XJrcovCt3BDqq1/K8pM4YsQ19+0ddl1vVgGlVosoonxSloOUUDKbFM7KYCFMT3KjdEu1dWdvg1Z9bc9Mc0WAGO8BrTIfuQxnKHWpTEj+jTJrzVv/jlRLCvoh0KEhc/Fowhkby6QsFlWWwGgK1zo7Sk6t9urfxNPwtVYZrL2ZSPtqjlCKeG4fvMf7NEYqWmCOv02Jmmhgc19agpxT1VcpByrZxPURPv1Frwek8ZI+2EH2hdccB7ZIUW3xxRKdw9siaYu/78BlJRlvsXCvrVj9ceVcj2qm+jy6ZxRNZ+X587OtQLZoLuIRFDIlJJzDQfvvbeiMNNyRCfBiKF0chnuGjt7lYGtonrCpuJ0rd+a4zLrosOX1OkecXetGF6ARdsTOovFwch9KXDCHklg8bSeUk696HsHbop3vf5sWnxkvqfu7SKI2J0rktY3LAYQlya7YyNGGCMVlAq5VXfMVR83qxfkuEPvp1M= # CODACY_PROJECT_TOKEN
  - secure: bbd/ih3o/rD8Bcv2YCA5okC08AVSMKtT7WO4FczCQt3ZH8OJci259HBLg299QzyqNmatkqxQWaEcDKoDCBUscKZf2IxEfKm9BZCvcTCnJks1wdabtvq9OK25iAMrASSIKG0pWsRVXfweyh8LZRaoj2nsTOzEl0gRXHv0XeylUk7O+ieabf56o69T8Lco4gVVSmJm4iQEtGra3c1hWUv/NFeN1x5vMmtKUGhjmhwrb1tSTk4ui5wWNwveleU+obdtVVth6kMNKCkXHyBqc72VDlbqzkujVA1ddOAnfZzmFFuJ9m6cCZXi/0QJsOMz68rS6B6n5WsrvWuI8ysKPGvI3Xd4meVTrG/mC6L1Af8sW3LJ72jPImHojsoqCcacXZSkvkk9H/7KmWYC/2EXS4xNqi32w6cboUMat98mt/qMQYkNxVKbzv5zlOlbWdMjhv0uHa0QVkMR7Q8P72TEsp8P6IRLwJSc5ZP2Pw1EUIVTn5AjjSEzVKhr0IZuBAlLrNxivZ2+JkE1HN5/ZUwcBes+oEpLvzNn/D0oTPOk3Ery/itxtyx0b6CVQTHdmbU60Z0JruLc2tFA6pk4F04efEVWhdmWQj9hwYCStfXkhaN/MCPvk6qvuI5B/aglEDmnRLkBeRmApyZuuQj8AEbWGJxwGeuttat+WPDAYDY3zBVxP50= # MAVEN_GPG_PASSPHRASE
  - secure: qCGRxwVkAakGatqeMIrdfoX41wxVY1TvvNBmah/JWzZWYfSJj91AYK7+/f/6Oe69cSkYCci7q0HT56u4DOlbLhhrZEo0IFOUd2UDM3XR865Sq4pDBiw2yiiEGyxnQcZ3Reca8RBa1/xN1uV5/B5I/mALboonpuHk9aRU0DD6siXlHUSwt/RJdCHNN2sXUBhTMk9svyFSCG8k+z6xXzHthnY7iWEtN2BCLvatCgYvc/VtYqeFCueWF58amvFtiFlAD+Wacm7ygnrZCXmWFStBrAn0jce93VsiFl1dFlTRYRYlFFvxFz/dTMsxIHhpnZBY75VzsZu+2rZx69SDkP5yk+ON51kSSGRU+xqykmW3p11+Oixy+q5Nh7eFCU0HcBTyvbR1qfnDN7Ersq69TSSOfxbXLT+gTIfVoJCG1SvuFV+sxvVn9vLsfUP3xqCo1eWJ+RFSAqe0aDmPKJYEveThHC4IdwalQerf1HrdL8LEEol0HCLfShEQU5Yw7vz7GAjuktnB4UXCQscchdLb4h/yUFCOfnTbr+nK3h5A0VStJkvwNESRS/os9BslJzG1Et0Lj74MSYNm9u1iUQP3Yej0s42GAZzeLVL6tYeUbv0VRVuNPFI3sPf5wR7v7bH2iuwwzelh08t4Kk11lz84EDzEZ4rqxgCBz0tu59UidkP0lSg= # MAVEN_SSRH_USERNAME
  - secure: hEWL8J/tNki16Sfu808hsXV+hB/olAp8k+5CHF72sGy+/5OBK+fQicvtma95JDwz9NCDk5QUSJUIfqYqmzUoDpyuwDcSVNIIOXU6hnaAm56YcD6fcFvU6rrWKuhpkwIJak04EqCZpcrkXXfeQrb+SQppaCBqPcCoNdaYSHVYFjh9KaIx41ShDktlostE9kKzzNS6/NlcuTOFD7zVPYLBZlBVBKBUnR5wlq9nw7QAyHuAZJzwnf6YNC60WJ8FNzwSldCQhAAptOLf7twX7+nphus72Rb4F92LZxhyJ1lmyO4c7Zv1/AfYijUy/wUiuzBAlt+cLFGgKLRA59V0dnYW7rUYcfq5J54zt1uaAZYOcFmq3m56iGufjFM3D6Eseq02fFhUxTCQ9Wm4b6HZQnVsEDx1klU9fS3NFNf13Y4QooapbSeSoVWP454VMTGiaxFcwq8wS5elKuMvkhzIFZvz6ER7aOD7/bmaNoeK4iWDtUEETGLtCfIiGCTOWwsnfvk+s0Q2qKugHYJdknI4A1E/b5pL56RxCbrz1n+xgHelzQezYf4HAn2J5xXujLQRIDvWtq4taNr+lA2J7boNkV7+YfnBO5TWoOBJSNL3c/OCIDM6OIKb5Ez5V8+QrEaPvVs7yMEVFJcYQOJOyvWRoqleXbLUU094X/QYpr3eC1vZ+dY= # MAVEN_OSSRH_PASSWORD
install:
- mvn dependency:go-offline -Pdependency-check
- mvn dependency:go-offline -Pcoverage
- mvn source:help javadoc:help -Prelease
before_script:
- mvn --update-snapshots dependency-check:check -Pdependency-check
script:
- mvn clean test jacoco:report verify -Pcoverage
cache:
  directories:
  - $HOME/.m2
before_deploy:
- "if ! gpg --list-secret-keys 34C80F11; then gpg --import 34C80F11.gpg; fi"
deploy:
- provider: script # SNAPSHOTS
  script: mvn clean deploy -DskipTests -Prelease --settings settings.xml
  skip_cleanup: true
  on:
    repo: cryptomator/webdav-nio-adapter
    branch: develop
    condition: $TRAVIS_TAG = ''
- provider: script # RELEASES
  script: mvn clean versions:set -DnewVersion=${TRAVIS_TAG} deploy -DskipTests -Prelease --settings settings.xml
  skip_cleanup: true
  on:
    repo: cryptomator/webdav-nio-adapter
    tags: true
